import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";
import CourselyLmsImg from "@/public/Coursely-lms.png";
import stackOverflowImg from "@/public/stackoverflow-clone.png";
import trelloCloneImg from "@/public/trello-clone.png";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "Graduation - Computer Science",
    location: "RGMCET, India",
    description:
      "I graduated after 4 years of studying. My most favorite subjects are Operating Systems, Computer Networks, Database Management systems and Web Technologies.",
    icon: React.createElement(LuGraduationCap),
    date: "2016-2020",
  },
  {
    title: "Post Graduation - Computer Science",
    location: "BITS Pilani, India",
    description:
      "I graduated after 2 years of studying. My most favorite subjects are Data Structures and Algorithms, Advanced Computer Networks, Advanced Operating Systems and Advanced Database Management systems.",
    icon: React.createElement(LuGraduationCap),
    date: "2021 - 2023",
  },
  {
    title: "Internship - Software Developer",
    location: "Western Digital, India",
    description:
      "I worked as a Software Developer Intern for 6 months. I worked on a project called 'Plot and Report Generation Tool For Logs' which is used to generate plots and reports from the logs generated by running different API tests on NAND chips.",
    icon: React.createElement(CgWorkAlt),
    date: "2023 Jan - 2023 June",
  },
  {
    title: "Self learning - Web Development",
    location: "",
    description:
      "After my internship, I gained proficiency in various cutting-edge technologies such as Next.js, React.js, Tailwind CSS, Framer Motion, Prisma, Drizzle, as well as databases including MySQL, PostgreSQL, and Redis. This hands-on experience enabled me to develop multiple production-ready web applications characterized by their mobile responsiveness. Furthermore, I successfully deployed these applications on platforms such as Vercel and AWS.",
    icon: React.createElement(CgWorkAlt),
    date: "2023 June - 2023 Nov",
  },
] as const;

export const projectsData = [
  {
    title: "StackOverflow Clone",
    description:
      "A public web app for asking questions and getting answers. It is a clone of StackOverflow.",
    tags: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind",
      "Zod",
      "Prisma",
      "MongoDB",
      "Zustand",
    ],
    imageUrl: stackOverflowImg,
    deploy: "https://stack-overflow-clone-alpha-pink.vercel.app/",
  },
  {
    title: "Trello Clone",
    description:
      "A public web app for managing tasks. It is a clone of Trello.",
    tags: ["React", "Next.js", "MySQL", "Tailwind", "React Beautiful DND"],
    imageUrl: trelloCloneImg,
    deploy: "https://trello-clone-alpha-nine.vercel.app/",
  },
] as const;

export const skillsData = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Tailwind",
  "React",
  "Next.js",
  "Node.js",
  "Express"
  "Git",
  "GitHub",
  "Prisma",
  "MongoDB",
  "MySQL",
  "tRPC",
  "Python",
  "Pandas",
  "Docker",
  "Zod",
  "Zustand",
] as const;
